/*
 * Simple LDAP Load Tester Example v0.1
 * $Source$
 * $Revision$
 * $Date$
 * $Author$
 */
/*
 * ldapblaster.h - simple ldap load tester
 */

///////////////
//           //
//  Fitlers  //
//           //
///////////////

   static char *filters[] = {
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=@pobox.alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=@polarnet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=@wildak.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=a.cousins_gx@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=alpineair@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=ammamariacolledgeqi@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=ap.258@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=archseiler_rv@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=benich@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=bjnelson@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=blivingston@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=buckeye@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=carlajoy@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=ccs@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=cherray@wildak.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=chiefeux@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=closeout@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=coffeeroasters@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=dhanns@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=dian@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=dkhanson@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=dmdieckg@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=dmoore@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=dodd@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=dryfoods@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=dsents@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=fam4x4@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=fhd@mosquitonet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=fkroger@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=fogwoman@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=forsale@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=foto@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=fourwair@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=gininalaska@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=good@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=hcox@mosquitonet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=heidi@mosquitonet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=idtraveler@mosquitonet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=jacaba@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=jbokanovichtf@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=jeremiah.stephen@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=jkdupree@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=joseph.carrico@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=joyful@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=jtyler@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=k.oliverog@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=kant@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=kblenkarn_lt@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=kidabilityst@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=logan@polarnet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=lorrel_taylor-hudson_im@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=lyons@mosquitonet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=macman@mosquitonet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=mamabear@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=markmtcbaselm@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=mehtaja@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=meltdown@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=mhall@pobox.alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=mraz@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=mst3k@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=mst3knut@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=mwgallagher@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=osa@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=otter@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=otterrv@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=pamarama@wildak.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=paulr@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=pierrettepratt_mq@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=pjryan@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=postmaster@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=ranger@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=rbeshears@mosquitonet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=rchughey@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=reulshop@pobox.alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=rhymes@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=roupen.titusin@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=rthieme@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=rthlsbrj@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=seabear@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=shayes@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=silverfx@wildak.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=snelon_ug@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=sonja@mosquitonet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=sonyasen@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=stephen@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=stephens@mosquitonet.com))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=sterling@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=steven@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=steveng@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=t.fuchsny@acsalaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=tietjen@xyz.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=tlwilson@pobox.alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=tnmc@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=tnn@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=tnndbn@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=tnns@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=tnoble@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=topjobs@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=translation@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=trauma@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=tspill@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=vangrd@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=vossenjp@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=whitesid@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=wingate@alaska.net))",
      "(&(|(inetMailGroupStatus=Active)(mailUserStatus=Active))(mail=woodard@acsalaska.net))",
      "(|(mail=HCOX@mosquitonet.com)(mailAlternateAddress=HCOX@mosquitonet.com)(MailEquivalentAddress=HCOX@mosquitonet.com))",
      "(|(mail=akjeep@mosquitonet.com)(mailAlternateAddress=akjeep@mosquitonet.com)(MailEquivalentAddress=akjeep@mosquitonet.com))",
      "(|(mail=fhd@mosquitonet.com)(mailAlternateAddress=fhd@mosquitonet.com)(MailEquivalentAddress=fhd@mosquitonet.com))",
      "(|(mail=lyons@mosquitonet.com)(mailAlternateAddress=lyons@mosquitonet.com)(MailEquivalentAddress=lyons@mosquitonet.com))",
      "(|(mail=macman@mosquitonet.com)(mailAlternateAddress=macman@mosquitonet.com)(MailEquivalentAddress=macman@mosquitonet.com))",
      "(|(mail=rbeshears@mosquitonet.com)(mailAlternateAddress=rbeshears@mosquitonet.com)(MailEquivalentAddress=rbeshears@mosquitonet.com))"
   };



