#strictflags = -O2 -Werror -Wall -pedantic -g -Wtraditional -W -Wimplicit -Wmain -Wparentheses -Wreturn-type -Wunused -Wswitch -Wcomment -Wformat -Wchar-subscripts -Wuninitialized -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline

#strictflags = -O2 -Werror -Wall -pedantic -g -Wtraditional -W -Wimplicit -Wmain -Wparentheses -Wreturn-type -Wunused -Wswitch -Wcomment -Wformat -Wchar-subscripts -Wuninitialized -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline

#strictflags = -O2 -Werror -Wall -pedantic -g -Wtraditional -W -Wimplicit -Wmain -Wparentheses -Wreturn-type -Wswitch -Wcomment -Wformat -Wchar-subscripts -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wconversion -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wredundant-decls -Wnested-externs -Winline

generalflags = -O2 -Werror -Wall -pedantic -g -Wtraditional -W

#generalflags = -O2 -Werror -Wall -pedantic -g -W

flags = -std=gnu99 $(generalflags)

ldaplib = -lldap -llber -lresolv 

all:
	gcc -g -o ldapsearch.o ldapsearch.c -lldap -llber -lresolv
	gcc -g -o ldapurl.o ldapurl.c -lldap -llber -lresolv
	gcc -o ldapblaster.o ldapblaster.c $(flags) $(ldaplib) -lncurses

clean:
	rm ./*.o
