#
# Makefile - make file for programming examples of 
#            allocating and freeing dynamic memory in C
# $Source$
# $Revision$
# $Date$
# $Author$
#

all: clean
	gcc -g -o getopt.o getopt.c

clean:
	if [ -f a.out ];then rm a.out;fi
	-rm -f *.o
